server:
  port: 8090  # Spring boot Server port

spring:
  config:
    activate:
      on-profile: h2Test
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb  #접속 URL
    username: test  # 사용자 이름 (로그인 시 사용)
    password:   # 사용자 암호 (로그인 시 사용)

  jpa:
    open-in-view: false #JPA를 잘 알아야 이해가 가능해서 생략
    generate-ddl: true #DDL 생성옵션
    show-sql: true #실행시 sql문을 보여줌
    hibernate:
      ddl-auto: create-drop
      #update - 서버를 재시작해도 초기화되지않음
      #create - 서버를 재시작할때마다 기존 테이블들을 drop하고 생성된 DDL을 실행함
      #create-drop - 언뜻보면 create와 비슷하지만 SessionFactiory가 종료될 때 drop을실행
      #validate - 변경된 스키마가 있으면 변경점을 출력 후 서버 종료
      #none - 아무것도 실행하지 않음(대부분의 DB에서 기본값)
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    com.project.health: debug

---
server:
  port: 8090  # Spring boot Server port
spring:
  config:
    activate:
      on-profile: local_mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.57:3306/coping?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: coping
    password: qwer!@#$

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    com.project.health: info
    org.hibernate.SQL: debug

---
server:
  port: 8090

spring:
  config:
    activate:
      on-profile: local_postgre
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.57:5432/coping
    username: postgres
    password: postgres
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
      defer-datasource-initialization: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    com.project.health: info
    org.hibernate.SQL: debug